# Generated by Django 2.0.5 on 2018-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('occupation', models.CharField(max_length=128)),
                ('place', models.CharField(max_length=128)),
            ],
        ),
    ]
